[package]
name = "chip8"
version = "0.1.0"
authors = ["Arnav Sastry <arnavsastry@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.17.*"
rand = "0.7.*"
tui = { version = "0.10.*", default-features = false, features = ["crossterm"] }
